# Generated by Django 4.1.7 on 2023-03-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/users_images/', verbose_name='User Image'),
        ),
    ]
