# Generated by Django 4.1.4 on 2023-01-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0003_remove_customuser_test_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Available_for',
            field=models.TextField(blank=True),
        ),
    ]
