# Generated by Django 4.1.4 on 2023-01-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0004_customuser_available_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
