# Generated by Django 4.1.4 on 2023-01-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0006_rename_available_for_customuser_available_for_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='website_url',
            new_name='website',
        ),
    ]
