# Generated by Django 4.1.4 on 2023-01-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0007_rename_website_url_customuser_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
