# Generated by Django 4.1.4 on 2023-01-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0008_rename_full_name_customuser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='available_for',
            field=models.TextField(blank=True, max_length=140),
        ),
    ]
